eventus/apps/events/urls.py
from django.conf.urls import url, include
from . import views
from .views import IndexView, MainPanelView, CreateEvent, EventDetail, EventEdit, EventDelete

app_name = 'events_app'

urlpatterns = [
	
	url(r'^$', IndexView.as_view(), name="index"),
	url(r'^panel/$', MainPanelView.as_view(), name="panel"),
	url(r'^panel/evento/nuevo$', CreateEvent.as_view(), name="nuevo"),
	url(r'^panel/evento/(?P<pk>\d+)/$', EventDetail.as_view(), name="detalle"),
	url(r'^panel/evento/editar/(?P<pk>\d+)/$', EventEdit.as_view(), name="editar"),
	url(r'^panel/evento/eliminar/(?P<pk>\d+)/$', EventDelete.as_view(), name="eliminar"),
	url(r'^panel/evento/(?P<pk>\d+)/$', views.create_comment, name="comment"),
]

eventus/apps/users/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'users_app'

urlpatterns = [
	url(r'^login/$', views.userlogin, name="login"),
	url(r'^signup/$', views.usersignup, name="signup"),
	url(r'^salir/$', views.LogOut, name='logout'),
]

eventus/eventus/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
	url(r'^', include('apps.events.urls'), name="events_app"),
    url(r'^', include('apps.users.urls'), name="users_app"),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,})

    ] 

eventus/apps/events/models.py
from __future__ import unicode_literals

from django.db import models
from django.template.defaultfilters import slugify
from django.conf import settings

class TimeStampModel(models.Model):
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now_add=True)

	class Meta:
		abstract = True

class Category(models.Model):
	name = models.CharField(max_length=50)
	slug = models.SlugField(editable=False)

	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = slugify(self.name)
		super(Category, self).save(*args,**kwargs)

	def __str__(self):
		return self.name

class Event(TimeStampModel):
	name = models.CharField(max_length=200, unique=True)
	slug = models.SlugField(editable=False)
	summary = models.TextField(max_length=255)
	content = models.TextField()
	category = models.ForeignKey(Category)
	place = models.CharField(max_length=50)
	start = models.DateTimeField()
	finish = models.DateTimeField()
	imagen = models.ImageField(upload_to = 'events') #Falta algo
	is_free = models.BooleanField(default=True)
	amoun = models.DecimalField(max_digits=5,decimal_places=2,default=0.00)
	views = models.PositiveIntegerField(default=0)
	organizer = models.ForeignKey(settings.AUTH_USER_MODEL) #Falta hacer algo

	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = slugify(self.name)
		super(Event, self).save(*args, **kwargs)

	def __str__(self):
		return self.name

class Assistant(TimeStampModel):

	assistant = models.ForeignKey(settings.AUTH_USER_MODEL) #Falta hacer algo
	event = models.ManyToManyField(Event)

	attended = models.BooleanField(default=False)
	has_paid = models.BooleanField(default=False)

	def __str__(self):
		return "%s %s" % (self.assistant.username, self.event.name)

class Comments(TimeStampModel):

	user = models.ForeignKey(settings.AUTH_USER_MODEL) #Falta hacer algo
	event = models.ForeignKey(Event)

	content = models.TextField()

	def __str__(self):
		return "%s %s" % (self.user.username, self.event.name)
	    

eventus/apps/events/forms.py
from django import forms
from .models import Event, Comments

class EventForm(forms.ModelForm):
	class Meta:
		model = Event
		exclude = ('views','created','modified','organizer')
		widgets = {
			'name': forms.TextInput(attrs={'class': 'form-control'}),
			'summary': forms.Textarea(attrs={'class': 'form-control', 'rows': '2'}),
			'content': forms.Textarea(attrs={'class': 'form-control', 'rows': '2'}),
			'category': forms.Select(attrs={'class': 'form-control'}),
			'place': forms.TextInput(attrs={'class': 'form-control'}),
			'start': forms.DateTimeInput(attrs={'class': 'form-control'}),
			'finish': forms.DateTimeInput(attrs={'class': 'form-control'}),
			'imagen': forms.ClearableFileInput(attrs={'class': 'form-control'}),
			'is_free': forms.CheckboxInput(attrs={'class': 'form-control'}),
			'amoun': forms.NumberInput(attrs={'class': 'form-control'}),
		}
class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comments
        exclude = {'user','event'}
        widgets = {
        	'content': forms.Textarea(attrs={'class': 'form-control', 'rows': '2'})
        }

    

eventus/apps/events/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView
from .models import Event, Category, Comments
from .forms import EventForm, CommentsForm
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth.models import User
from braces.views import LoginRequiredMixin, SuperuserRequiredMixin

# Create your views here.

#def index(request):
#	events = Event.objects.all().order_by('		-created')[:6]
#	categories = Category.objects.all()
#	return render(request, 'events/index.html', {'events': events, 'categories':categories})
class IndexView(TemplateView):
	template_name = 'events/index.html'
	def get_context_data(self, **kwargs):
		context = super(IndexView, self).get_context_data(**kwargs)
		context['events'] = Event.objects.all().order_by('-created')[:6]
		context['categories'] = Category.objects.all()
		return context


#def main_panel(request):
#	events = Event.objects.filter(organizer__username='AlanHedz').order_by('is_free', '-created')
#	cantidad_eventos = events.count()
#	return render(request,'events/panel/panel.html', {'events': events, 'cantidad': cantidad_eventos})
class MainPanelView(LoginRequiredMixin, TemplateView):
	login_url = 'users_app:login'
	template_name = 'events/panel/panel.html'
	def get_context_data(self, **kwargs):
		context = super(MainPanelView, self).get_context_data(**kwargs)
		context['events'] = Event.objects.filter(organizer = self.request.user).order_by('is_free', '-created')
		context['cantidad'] = context['events'].count()
		return context

#def crear_evento(request):
#	if request.method == 'POST':
#		modelform = EventForm(request.POST, request.FILES)
#		if modelform.is_valid():
#			organizador = User.objects.get(pk="1")
#			nuevo_evento = modelform.save()
#			nuevo_evento.organizer = organizador
#			nuevo_evento.save()
#			return redirect(reverse('events_app:panel'))
#	else:
#		modelform = EventForm()
#
#	return render(request, 'events/panel/crear_evento.html', {'form': modelform})
class CreateEvent(LoginRequiredMixin, CreateView):
	login_url = 'users_app:login'
	form_class = EventForm
	template_name = "events/panel/crear_evento.html"
	success_url = reverse_lazy('events_app:panel')

	def form_valid(self,form):
		form.instance.organizer = self.request.user
		return super(CreateEvent, self).form_valid(form)


#def detalle_evento(request, evento_id):
#	event = get_object_or_404(Event, pk=evento_id)
#	return render(request, 'events/panel/detalle_evento.html',{'event': event})
class EventDetail(DetailView):
	template_name = "events/panel/detalle_evento.html"
	model = Event

#def editar_evento(request, evento_id):
#	event = get_object_or_404(Event, pk=evento_id)
#
#	if request.method == 'POST':
#		modelform = EventForm(request.POST, request.FILES, instance=event)
#		if modelform.is_valid():
#			modelform.save()
#			return redirect(reverse('events_app:panel'))
#	else:
#		modelform = EventForm(instance=event)
#
#	return render(request, 'events/panel/editar_evento.html', {'form': modelform, 'event': event})
class EventEdit(LoginRequiredMixin, UpdateView):
	login_url = 'users_app:login'
	template_name = 'events/panel/editar_evento.html'
	model = Event
	form_class = EventForm
	success_url = reverse_lazy('events_app:panel')

	def form_valid(self,form):
		form.instance.organizer = self.request.user
		return super(EventEdit, self).form_valid(form)

#def eliminar_evento(request, evento_id):
#	event = get_object_or_404(Event, pk=evento_id)
#
#	if request.method == 'POST':
#		event.delete()
#		return redirect(reverse('events_app:panel'))
#
#	return render(request, 'events/panel/eliminar_evento.html', {'event': event})
class EventDelete(SuperuserRequiredMixin, LoginRequiredMixin, DeleteView):
	login_url = 'users_app:login'
	template_name = 'events/panel/eliminar_evento.html'
	model = Event
	succes_url = reverse_lazy('events_app:panel')
	context_object_name = 'event'

def create_comment(request):
	post = get_object_or_404(Post, pk=pk)
	if request.method == 'POST':
		modelform = CommentsForm(request.POST)
		if modelform.is_valid():
			nuevo_comentario = modelform.save()
			nuevo_comentario.user = self.request.user
			nuevo_comentario.event = post
			return redirect(reverse('events_app:detalle'))
	else:
		modelform = CommentsForm()

	return render(request, 'events/panel/detalle_evento.html', {'form': modelform})

eventus/apps/events/templates/events/base_events.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
	<link rel="stylesheet" href="{% static 'css/estilos.css' %}">
{% endblock css %}
{% block js %}
	<script src="https://code.jquery.com/jquery-2.1.4.js"></script>
	<script src="{% static 'js/bootstrap.js' %}"></script>
{% endblock js %}

eventus/apps/events/templates/events/index.html
{% extends "events/base_events.html" %}

{% block title %}Home{% endblock title %}

{% block content %}

{% include "events/nav.html" %}

<div class="jumbotron">
  <div class="container text-center">
    <h1>EVENTUS</h1>
    <p>Bienvenido a EVENTUS, aquí podrás encontrar eventos que se den en tu ciudad e inscribirte on-line con un solo click.</p>
    <p>¡<a href="{% url 'users_app:login' %}" role="button">Registrate</a> y crea tu evento ahora!</p>
  </div>
</div>

<div class="container">

    <div class="page-header">
        <h4><strong>Eventos disponibles</strong></h4>
    </div>

    <div class="row">
        
        <div class="col-md-2">
            <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-tag"></span></span>
                <select class="form-control">
                    <option>Categoría</option>
                </select>
            </div>
        </div>
        <div class="col-md-2">
            <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-credit-card"></span></span>
            <select class="form-control">
                <option>Tipo pago</option>
            </select>
            </div>
        </div>
        <div class="col-md-8">
            <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>
                <input type="text" class="form-control" placeholder="Busca el evento de tu gusto">
            </div>
        </div>

    </div>

</div>

<p></p>

<div class="container eventos">    
    
    <div class="row contenedor-eventos">
        {% for event in events %}
        <div class="col-sm-1 col-md-3 ">
            <div class="thumbnail equal">
                <img src="{{ event.imagen.url }}" alt="250x180">
                <div class="caption">
                    <h4><a href="{% url 'events_app:detalle' event.id %}">{{ event.name }}</a></h4>
                    <small class="date">{{ event.start }}</small>
                    <div class="place">
                        <small class="place">{{ event.place}}</small> / 
                    </div>
                    <span class="views">{{ event.views }}</span>
                </div>
            </div>
        </div>
        {% endfor %}
        
    </div>

</div>

<div class="container categorias">    

    <div class="page-header">
        <h4><strong>Categorías relacionadas</strong></h4>
    </div>

    <div class="row">
        <div class="col-sm-1 col-md-12">
        {% for category in categories %}
            <a class="btn btn-default btn-lg btn-fix">
                <span class="glyphicon glyphicon-tag"></span> {{ category.name }}
            </a>
        {% endfor %}
        </div>

    </div>

</div>

<div class="container organizadores">    

    <div class="page-header">
        <h4><strong>Organizadores destacados</strong></h4>
    </div>

    <div class="row">

        <div class="col-sm-1 col-md-2">
            <div class="thumbnail">
                <img src="http://placehold.it/300x180" alt="250x180">
                <div class="caption">
                    Nombre organizador
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock content %}

eventus/apps/events/templates/events/nav.html
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'events_app:index' %}">Eventus</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav pull-right">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'events_app:panel' %}">{{ user.username }}</a></li>
                    <li><a href="{% url 'users_app:logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'users_app:signup' %}">Sign Up</a></li>
                    <li><a href="{% url 'users_app:login' %}">Login</a></li>
                {% endif %}  
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>