eventus/apps/events/urls.py
from django.conf.urls import url, include
from . import views
from .views import IndexView, MainPanelView, CreateEvent, EventDetail, EventEdit, EventDelete

app_name = 'events_app'

urlpatterns = [
	
	url(r'^$', IndexView.as_view(), name="index"),
	url(r'^panel/$', MainPanelView.as_view(), name="panel"),
	url(r'^panel/evento/nuevo$', CreateEvent.as_view(), name="nuevo"),
	url(r'^panel/evento/(?P<pk>\d+)/$', EventDetail.as_view(), name="detalle"),
	url(r'^panel/evento/editar/(?P<pk>\d+)/$', EventEdit.as_view(), name="editar"),
	url(r'^panel/evento/eliminar/(?P<pk>\d+)/$', EventDelete.as_view(), name="eliminar"),
	url(r'^panel/evento/(?P<pk>\d+)/$', views.create_comment, name="comment"),
]

eventus/eventus/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
	url(r'^', include('apps.events.urls'), name="events_app"),
    url(r'^', include('apps.users.urls'), name="users_app"),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,})

    ] 

eventus/apps/events/models.py
from __future__ import unicode_literals

from django.db import models
from django.template.defaultfilters import slugify
from django.conf import settings

class TimeStampModel(models.Model):
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now_add=True)

	class Meta:
		abstract = True

class Category(models.Model):
	name = models.CharField(max_length=50)
	slug = models.SlugField(editable=False)

	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = slugify(self.name)
		super(Category, self).save(*args,**kwargs)

	def __str__(self):
		return self.name

class Event(TimeStampModel):
	name = models.CharField(max_length=200, unique=True)
	slug = models.SlugField(editable=False)
	summary = models.TextField(max_length=255)
	content = models.TextField()
	category = models.ForeignKey(Category)
	place = models.CharField(max_length=50)
	start = models.DateTimeField()
	finish = models.DateTimeField()
	imagen = models.ImageField(upload_to = 'events') #Falta algo
	is_free = models.BooleanField(default=True)
	amoun = models.DecimalField(max_digits=5,decimal_places=2,default=0.00)
	views = models.PositiveIntegerField(default=0)
	organizer = models.ForeignKey(settings.AUTH_USER_MODEL) #Falta hacer algo

	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = slugify(self.name)
		super(Event, self).save(*args, **kwargs)

	def __str__(self):
		return self.name

class Assistant(TimeStampModel):

	assistant = models.ForeignKey(settings.AUTH_USER_MODEL) #Falta hacer algo
	event = models.ManyToManyField(Event)

	attended = models.BooleanField(default=False)
	has_paid = models.BooleanField(default=False)

	def __str__(self):
		return "%s %s" % (self.assistant.username, self.event.name)

class Comments(TimeStampModel):

	user = models.ForeignKey(settings.AUTH_USER_MODEL) #Falta hacer algo
	event = models.ForeignKey(Event)

	content = models.TextField()

	def __str__(self):
		return "%s %s" % (self.user.username, self.event.name)
	    

eventus/apps/events/forms.py
from django import forms
from .models import Event, Comments

class EventForm(forms.ModelForm):
	class Meta:
		model = Event
		exclude = ('views','created','modified','organizer')
		widgets = {
			'name': forms.TextInput(attrs={'class': 'form-control'}),
			'summary': forms.Textarea(attrs={'class': 'form-control', 'rows': '2'}),
			'content': forms.Textarea(attrs={'class': 'form-control', 'rows': '2'}),
			'category': forms.Select(attrs={'class': 'form-control'}),
			'place': forms.TextInput(attrs={'class': 'form-control'}),
			'start': forms.DateTimeInput(attrs={'class': 'form-control'}),
			'finish': forms.DateTimeInput(attrs={'class': 'form-control'}),
			'imagen': forms.ClearableFileInput(attrs={'class': 'form-control'}),
			'is_free': forms.CheckboxInput(attrs={'class': 'form-control'}),
			'amoun': forms.NumberInput(attrs={'class': 'form-control'}),
		}
class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comments
        exclude = {'user','event'}
        widgets = {
        	'content': forms.Textarea(attrs={'class': 'form-control', 'rows': '2'})
        }

    

eventus/apps/events/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView
from .models import Event, Category, Comments
from .forms import EventForm, CommentsForm
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth.models import User
from braces.views import LoginRequiredMixin, SuperuserRequiredMixin

# Create your views here.

#def index(request):
#	events = Event.objects.all().order_by('		-created')[:6]
#	categories = Category.objects.all()
#	return render(request, 'events/index.html', {'events': events, 'categories':categories})
class IndexView(TemplateView):
	template_name = 'events/index.html'
	def get_context_data(self, **kwargs):
		context = super(IndexView, self).get_context_data(**kwargs)
		context['events'] = Event.objects.all().order_by('-created')[:6]
		context['categories'] = Category.objects.all()
		return context


#def main_panel(request):
#	events = Event.objects.filter(organizer__username='AlanHedz').order_by('is_free', '-created')
#	cantidad_eventos = events.count()
#	return render(request,'events/panel/panel.html', {'events': events, 'cantidad': cantidad_eventos})
class MainPanelView(LoginRequiredMixin, TemplateView):
	login_url = 'users_app:login'
	template_name = 'events/panel/panel.html'
	def get_context_data(self, **kwargs):
		context = super(MainPanelView, self).get_context_data(**kwargs)
		context['events'] = Event.objects.filter(organizer = self.request.user).order_by('is_free', '-created')
		context['cantidad'] = context['events'].count()
		return context

#def crear_evento(request):
#	if request.method == 'POST':
#		modelform = EventForm(request.POST, request.FILES)
#		if modelform.is_valid():
#			organizador = User.objects.get(pk="1")
#			nuevo_evento = modelform.save()
#			nuevo_evento.organizer = organizador
#			nuevo_evento.save()
#			return redirect(reverse('events_app:panel'))
#	else:
#		modelform = EventForm()
#
#	return render(request, 'events/panel/crear_evento.html', {'form': modelform})
class CreateEvent(LoginRequiredMixin, CreateView):
	login_url = 'users_app:login'
	form_class = EventForm
	template_name = "events/panel/crear_evento.html"
	success_url = reverse_lazy('events_app:panel')

	def form_valid(self,form):
		form.instance.organizer = self.request.user
		return super(CreateEvent, self).form_valid(form)


#def detalle_evento(request, evento_id):
#	event = get_object_or_404(Event, pk=evento_id)
#	return render(request, 'events/panel/detalle_evento.html',{'event': event})
class EventDetail(DetailView):
	template_name = "events/panel/detalle_evento.html"
	model = Event

#def editar_evento(request, evento_id):
#	event = get_object_or_404(Event, pk=evento_id)
#
#	if request.method == 'POST':
#		modelform = EventForm(request.POST, request.FILES, instance=event)
#		if modelform.is_valid():
#			modelform.save()
#			return redirect(reverse('events_app:panel'))
#	else:
#		modelform = EventForm(instance=event)
#
#	return render(request, 'events/panel/editar_evento.html', {'form': modelform, 'event': event})
class EventEdit(LoginRequiredMixin, UpdateView):
	login_url = 'users_app:login'
	template_name = 'events/panel/editar_evento.html'
	model = Event
	form_class = EventForm
	success_url = reverse_lazy('events_app:panel')

	def form_valid(self,form):
		form.instance.organizer = self.request.user
		return super(EventEdit, self).form_valid(form)

#def eliminar_evento(request, evento_id):
#	event = get_object_or_404(Event, pk=evento_id)
#
#	if request.method == 'POST':
#		event.delete()
#		return redirect(reverse('events_app:panel'))
#
#	return render(request, 'events/panel/eliminar_evento.html', {'event': event})
class EventDelete(SuperuserRequiredMixin, LoginRequiredMixin, DeleteView):
	login_url = 'users_app:login'
	template_name = 'events/panel/eliminar_evento.html'
	model = Event
	succes_url = reverse_lazy('events_app:panel')
	context_object_name = 'event'

def create_comment(request):
	post = get_object_or_404(Post, pk=pk)
	if request.method == 'POST':
		modelform = CommentsForm(request.POST)
		if modelform.is_valid():
			nuevo_comentario = modelform.save()
			nuevo_comentario.user = self.request.user
			nuevo_comentario.event = post
			return redirect(reverse('events_app:detalle'))
	else:
		modelform = CommentsForm()

	return render(request, 'events/panel/detalle_evento.html', {'form': modelform})

eventus/apps/events/templates/events/panel/crear_evento.html
{% extends "events/base_events.html" %}

{% block title %}Panel{% endblock title %}

{% block content %}

    {% include "events/nav.html" %}
    <div class="container">

        <div class="page-header">
            <h4>
                <a href="{% url 'events_app:panel' %}" class="btn btn-success">
                    <span class="glyphicon glyphicon-chevron-left"></span> Regresar
                </a>
                <strong>Crear evento</strong>
            </h4>
        </div><!-- page-header -->

        <div class="row">
            
            <div class="col-md-12">

                <form role="form" method="POST" enctype="multipart/form-data">{% csrf_token %}
                    <p class="lead"><span class="glyphicon glyphicon-info-sign"></span> Ingresa los datos de tu evento y compartelo con todos tus conocidos o amigos.</p>

                    {% if form.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ form.errors }}
                        </div>
                    {% endif %}

                    <div class="form-group">
                        <label>{{ form.name.label_tag }}</label>
                        {{ form.name }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.summary.label_tag }}</label>
                        {{ form.summary }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.content.label_tag }}</label>
                        {{ form.content }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.category.label_tag }}</label>
                        {{ form.category }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.place.label_tag }}</label>
                        {{ form.place }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.start.label_tag }}</label>
                        {{ form.start }}
                        <p class="help-block">Ingresa cuando inciará el evento. DD/MM/AA HH:MM:SS.</p>
                    </div>

                    <div class="form-group">
                        <label>{{ form.finish.label_tag }}</label>
                        {{ form.finish }}
                        <p class="help-block">Ingresa cuando finalizará el evento. DD/MM/AA HH:MM:SS.</p>
                    </div>

                    <div class="form-group">
                        <label>{{ form.imagen.label_tag }}</label>
                        {{ form.imagen }}
                    </div>

                    <div class="checkbox">
                        <label>
                            {{ form.is_free }} {{ form.is_free.label_tag }}
                        </label>
                    </div>
                    
                    <div class="form-group">
                        <label>{{ form.amoun.label }}</label>
                        {{ form.amoun }}
                    </div>
                    
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Guardar evento</button>
                    </div>
                </form>

            </div><!-- col-md-12 -->

        </div><!-- /row -->

    </div><!-- /container -->

{% endblock content %}

eventus/apps/events/templates/events/panel/detalle_evento.html
{% extends "events/base_events.html" %}
{% block title %}Panel{% endblock title %}

{% block content %}

{% include "events/nav.html" %}
    <div class="container">

        <div class="page-header">
            <h4>
                {% if user.is_authenticated %}
                    <a href="{% url 'events_app:panel' %}" class="btn btn-success">
                        <span class="glyphicon glyphicon-chevron-left"></span> Regresar
                    </a>
                {% else %}
                    <a href="{% url 'events_app:index' %}" class="btn btn-success">
                        <span class="glyphicon glyphicon-chevron-left"></span> Regresar
                    </a>            
                {% endif %}
                <strong>Evento: {{ event.name }}</strong>
            </h4>
        </div><!-- page-header -->

        <div class="row">
            
            <div class="col-md-3 text-center">
                <img src="{{ event.imagen.url }}" alt="250x180" class="img-rounded" style="height: 200px;">
            </div>

            <div class="col-md-9">

                <table class="table">
                    <tbody>
                        <tr>
                            <th>Name</th>
                            <td>{{ event.name }}</td>
                        </tr>
                        <tr>
                            <th>Category</th>
                            <td>{{ event.category }}</td>
                        </tr>
                        <tr>
                            <th>Content</th>
                            <td>{{ event.content }}</td>
                        </tr>
                        <tr>
                            <th>Start / Finish</th>
                            <td>{{ event.start }} / {{ event.finish }}</td>
                        </tr>
                        <tr>
                            <th>Place</th>
                            <td>{{ event.place }}</td>
                        </tr>
                        <tr>
                            <th>Amount</th>
                            {% if event.is_free %}
                                <td><span class="label label-default">Gratuito</span></td>
                            {% else %}
                                <td><span class="label label-info">S/. {{ event.amoun }}</span></td>
                            {% endif %}
                        </tr>
                    </tbody>
                </table>

            </div><!-- col-md-12 -->

        </div><!-- /row -->
        <div>
            <form role="form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div>
                    {{form.content}}
                </div>
                <div class="form-group">
                        <button type="submit" class="btn btn-primary">Guardar evento</button>
                </div>
            </form>
        </div>
    </div><!-- /container -->

{% endblock content %}

eventus/apps/events/templates/events/panel/editar_evento.html
{% extends "events/base_events.html" %}
{% block title %}Panel{% endblock title %}

{% block content %}
    {% include 'events/nav.html' %}
    <div class="container">

        <div class="page-header">
            <h4>
                <a href="{% url 'events_app:panel' %}" class="btn btn-success">
                    <span class="glyphicon glyphicon-chevron-left"></span> Regresar
                </a>
                <strong>Editando: {{ event.name }}</strong>
            </h4>
        </div><!-- page-header -->

        <div class="row">
            
            <div class="col-md-12">

                <form role="form" action="{% url 'events_app:editar' event.id %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
                    <p class="lead"><span class="glyphicon glyphicon-info-sign"></span> Ingresa los datos del evento para cambiar los datos.</p>

                    {% if form.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ form.errors }}
                        </div>
                    {% endif %}

                    <div class="form-group">
                        <label>{{ form.name.label_tag }}</label>
                        {{ form.name }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.summary.label_tag }}</label>
                        {{ form.summary }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.content.label_tag }}</label>
                        {{ form.content }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.category.label_tag }}</label>
                        {{ form.category }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.place.label_tag }}</label>
                        {{ form.place }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.start.label_tag }}</label>
                        {{ form.start }}
                        <p class="help-block">Ingresa cuando inciará el evento. DD/MM/AA HH:MM:SS.</p>
                    </div>

                    <div class="form-group">
                        <label>{{ form.finish.label_tag }}</label>
                        {{ form.finish }}
                        <p class="help-block">Ingresa cuando finalizará el evento. DD/MM/AA HH:MM:SS.</p>
                    </div>

                    <div class="form-group">
                        <label>{{ form.imagen.label_tag }}</label>
                        {{ form.imagen }}
                    </div>

                    <div class="checkbox">
                        <label>
                            {{ form.is_free }} {{ form.is_free.label_tag }}
                        </label>
                    </div>
                    
                    <div class="form-group">
                        <label>{{ form.amoun.label }}</label>
                        {{ form.amoun }}
                    </div>
                    
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Guardar evento</button>
                    </div>
                </form>

            </div><!-- col-md-12 -->

        </div><!-- /row -->

    </div><!-- /container -->
{% endblock content %}	

eventus/apps/events/templates/events/panel/eliminar_evento.html
{% extends "events/base_events.html" %}

{% block title %}Panel{% endblock title %}

{% block content %}

    {% include "events/nav.html" %}

    <div class="container">

        <div class="page-header">
            <h4>
                <strong>Eliminando: {{ event.name }}</strong>
            </h4>
        </div><!-- page-header -->

        <div class="row">
            
            <div class="col-md-12">

                <form role="form" action="{% url 'events_app:eliminar' event.id %}" method="POST">{% csrf_token %}
                    <p class="">¿Desea eliminar el evento "{{ event.name }}"?</p>

                    <input type="submit" value="Sí" class="btn btn-danger"> 
                    <a href="{% url 'events_app:panel' %}" class="btn btn-default">No</a>
                </form>

            </div><!-- col-md-12 -->

        </div><!-- /row -->

    </div><!-- /container -->

{% endblock content %}

eventus/apps/events/templates/events/panel/panel.html
{% extends "events/base_events.html" %}

{% block content %}

{% include "events/nav.html" %}
 	
    <div class="container">

        <div class="page-header">
            <h4>
                <strong>Tienes <span class="label label-warning">{{ cantidad }}</span> Eventos disponibles </strong>
                <a class="btn btn-primary pull-right" href="{% url 'events_app:nuevo' %}">
                    <span class="glyphicon glyphicon-plus"></span> Crear un evento nuevo
                </a>
            </h4>
        </div><!-- page-header -->

        <div class="row">
            
            <div class="col-md-12">
                
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th colspan="2">Nombre del evento</th>
                            <th>Categoría</th>
                            <th>Inicio</th>
                            <th>Fin</th>
                            <th>Monto</th>
                            <th class="text-center">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for event in events %}
                        <tr>
                            <td>
                                <img src="{{ event.imagen.url }}" alt="{{ event.name }}" width="60" class="img-rounded">
                            </td>
                            <td>{{ event.name }}</td>
                            <td>{{ event.category }}</td>
                            <td>{{ event.start }}</td>
                            <td>{{ event.finish }}</td>
                            <td>
                                {% if event.is_free %}
                                    <span class="label label-default">Gratuito</span>
                                {% else %}
                                    <span class="label label-info">S/. {{ event.amoun }}</span>
                                {% endif %}
                            </td>
                            <td class="text-right">
                                <a href="{% url 'events_app:detalle' event.id %}" class="btn btn-success"><span class="glyphicon glyphicon-eye-open"></span></a>
                                <a href="{% url 'events_app:editar' event.id %}" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
                                <a href="{% url 'events_app:eliminar' event.id %}" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div><!-- col-md-12 -->

        </div><!-- /row -->

    </div><!-- /container -->

{% endblock content %}